SELECT
    PRODUCTID
    , CATEGORY
    , PRODUCTNAME
    , SUBCATEGORY
    , SUM(ORDER_PROFIT) AS PROFIT
FROM
{{ ref('STG_ORDERS') }}
GROUP BY
    PRODUCTID
    , CATEGORY
    , PRODUCTNAME
    , SUBCATEGORY
